### PR TITLE
Add stochSim to params sent to backend

### PR DESCRIPTION
**Pull request by pmac**
The backend is already updated so it's expected that requests will fail until it is sending the new param.

### CODE REVIEW

**Comment by pmac** [comment]
I also updated it to be a bit more compatible with more browsers (IE).

**Comment by pmac** [comment]
@letsgoexploring does github send you emails about this without me mentioning you directly?

**Comment by letsgoexploring** [comment]
OK I think I set up the js to send the new param stochSim.checked. I'm
still seeing an error so maybe the python code isn't receiving the correct
variable value? It should be a boolean.

**Comment by pmac** [comment]
I sent a PR. Might not have notified you. When you try to send a boolean in this way it just sends the word "true", which isn't that helpful. So I convert it to a 1 or 0 and that works fine after we convert to int on the python side.


On December 21, 2017 at 12:01:18, Brian C Jenkins (notifications@github.com) wrote:

OK I think I set up the js to send the new param stochSim.checked. I'm
still seeing an error so maybe the python code isn't receiving the correct
variable value? It should be a boolean.

**Comment by letsgoexploring** [comment]
I don't see any pull requests.

**Comment by pmac** [comment]
Yeah, sorry, was confused. This is the pull request :)

**Comment by pmac** [comment]
I'll update this PR. Looks like there have been changes since I submitted.

**Comment by pmac** [comment]
Oh yeah, can't just send checked, but also can't do that with the shorthand notation I was using. This PR converts to using a normal JS object instead of that shorthand so it's less confusing and more broadly compatible with browsers.

**Comment by pmac** [comment]
Okay. PR updated. I believe if you try this it should work.

**Comment by pmac** [comment]
Sending JSON around is nice because you do have some basic types like int, float, and boolean, but that's not the case with URL paramaters in a GET request like we're doing.

**Comment by letsgoexploring** [comment]
It works! Thanks!!

**Pull request merged**
